# Copyright (C) 2024 Cetmix OÜ
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import _, fields, models
from odoo.exceptions import ValidationError


class CxTowerJetWaypointTemplate(models.Model):
    """Jet Waypoint Templates define waypoints for jet templates"""

    _name = "cx.tower.jet.waypoint.template"
    _description = "Cetmix Tower Jet Waypoint Template"
    _inherit = ["cx.tower.reference.mixin", "cx.tower.access.mixin"]
    _order = "name asc"

    name = fields.Char(required=True)
    jet_template_id = fields.Many2one(
        comodel_name="cx.tower.jet.template",
        required=True,
        ondelete="cascade",
        help="Jet template this waypoint template belongs to",
    )
    plan_create_id = fields.Many2one(
        string="Create Flight Plan",
        comodel_name="cx.tower.plan",
        help="Flight plan to run after waypoint is created",
    )
    plan_arrive_id = fields.Many2one(
        string="Arrive Flight Plan",
        comodel_name="cx.tower.plan",
        help="Flight plan to run after waypoint is reached",
    )
    plan_leave_id = fields.Many2one(
        string="Leave Flight Plan",
        comodel_name="cx.tower.plan",
        help="Flight plan to run before leaving the waypoint",
    )
    plan_delete_id = fields.Many2one(
        string="Delete Flight Plan",
        comodel_name="cx.tower.plan",
        help="Flight plan to run before deleting the waypoint",
    )
    note = fields.Text()

    def create_waypoint(self, jet, name=None, **kwargs):
        """
        Create a new waypoint for the given jet

        Args:
            jet (cx.tower.jet): Jet to create the waypoint for
            name (str): Name of the waypoint
            kwargs: Additional values to create the waypoint
        Returns:
            cx.tower.jet.waypoint: The created waypoint
        """
        self.ensure_one()
        if not jet.jet_template_id == self.jet_template_id:
            raise ValidationError(
                _("Jet template does not match the waypoint template")
            )

        waypoint = self.env["cx.tower.jet.waypoint"].create(
            self._prepare_waypoint_values(jet, name, **kwargs)
        )
        return waypoint

    def _prepare_waypoint_values(self, jet, name=None, **kwargs):
        """
        Prepare the waypoint values to create a new waypoint for the given jet
        """
        self.ensure_one()
        return {
            "name": name if name else _("Autogenerated"),
            "jet_id": jet.id,
            "waypoint_template_id": self.id,
            **kwargs,
        }
